[package]
edition = "2021"
name = "ocr-rust"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = {version = "0.6.20", features = ['multipart']}
cv_self = {path = './cv_self'}
opencv = "0.86.1"
tokio = {version = "1.34.0", features = ["full"]}

[workspace]
menbers = ['.', 'cv_self']
